#!/bin/bash

echo "Run count Node tests with options $@..."

# 2 denotes the Node test
# 9 is the number of tests (the different ways we iterate)
# 2...12 denotes the number of arguments of the TNode we are iterating over
./perf_test_script 2 11 2 $@
./perf_test_script 2 11 3 $@
./perf_test_script 2 11 4 $@
./perf_test_script 2 11 5 $@
./perf_test_script 2 11 6 $@
./perf_test_script 2 11 7 $@
./perf_test_script 2 11 8 $@
./perf_test_script 2 11 9 $@
./perf_test_script 2 11 10 $@
./perf_test_script 2 11 11 $@
./perf_test_script 2 11 12 $@
