#!/bin/bash

echo "Run count std::vector Node tests with options $@..."

./perf_test_script 1 7 2 $@ 
./perf_test_script 1 7 3 $@
./perf_test_script 1 7 4 $@
./perf_test_script 1 7 5 $@
./perf_test_script 1 7 6 $@
./perf_test_script 1 7 7 $@
./perf_test_script 1 7 8 $@
./perf_test_script 1 7 9 $@
./perf_test_script 1 7 10 $@
./perf_test_script 1 7 11 $@
./perf_test_script 1 7 12 $@
