#!/bin/bash

echo "Run count vector tests with options $@..."

./perf_test_script 1 6 2 $@ 
./perf_test_script 1 6 3 $@
./perf_test_script 1 6 4 $@
./perf_test_script 1 6 5 $@
./perf_test_script 1 6 6 $@
./perf_test_script 1 6 7 $@
./perf_test_script 1 6 8 $@
./perf_test_script 1 6 9 $@
./perf_test_script 1 6 10 $@
./perf_test_script 1 6 11 $@
./perf_test_script 1 6 12 $@
