#!/bin/bash

echo "Run count std::unordered_map test with options $@..."

./perf_test_script 4 9 2 $@ 
./perf_test_script 4 9 3 $@
./perf_test_script 4 9 4 $@
./perf_test_script 4 9 5 $@
./perf_test_script 4 9 6 $@
./perf_test_script 4 9 7 $@
./perf_test_script 4 9 8 $@
./perf_test_script 4 9 9 $@
./perf_test_script 4 9 10 $@
./perf_test_script 4 9 11 $@
./perf_test_script 4 9 12 $@

