#!/bin/bash

echo "Run count data structure tests with options $@..."

./perf_test_script 3 9 2 $@ 
./perf_test_script 3 9 3 $@
./perf_test_script 3 9 4 $@
./perf_test_script 3 9 5 $@
./perf_test_script 3 9 6 $@
./perf_test_script 3 9 7 $@
./perf_test_script 3 9 8 $@
./perf_test_script 3 9 9 $@
./perf_test_script 3 9 10 $@
./perf_test_script 3 9 11 $@
./perf_test_script 3 9 12 $@

