#!/bin/bash

echo "Run count vector tests with options $@..."

./perf_test_script 1 2 $@ 
./perf_test_script 1 3 $@
./perf_test_script 1 4 $@
./perf_test_script 1 5 $@
./perf_test_script 1 6 $@
./perf_test_script 1 7 $@
./perf_test_script 1 8 $@
./perf_test_script 1 9 $@
./perf_test_script 1 10 $@
./perf_test_script 1 11 $@
./perf_test_script 1 12 $@
