#!/bin/bash

echo "Run count data structure tests with options $@..."

./perf_test_script 3 12 2 $@ 
./perf_test_script 3 12 3 $@
./perf_test_script 3 12 4 $@
./perf_test_script 3 12 5 $@
./perf_test_script 3 12 6 $@
./perf_test_script 3 12 7 $@
./perf_test_script 3 12 8 $@
./perf_test_script 3 12 9 $@
./perf_test_script 3 12 10 $@
./perf_test_script 3 12 11 $@
./perf_test_script 3 12 12 $@

