#!/bin/bash

echo "Run count data structure tests with options $@..."

./perf_test_script 3 16 2 $@ 
./perf_test_script 3 16 3 $@
./perf_test_script 3 16 4 $@
./perf_test_script 3 16 5 $@
./perf_test_script 3 16 6 $@
./perf_test_script 3 16 7 $@
./perf_test_script 3 16 8 $@
./perf_test_script 3 16 9 $@
./perf_test_script 3 16 10 $@
./perf_test_script 3 16 11 $@
./perf_test_script 3 16 12 $@

