#!/bin/bash

echo "Run count std::vector TNode tests with options $@..."

# 6 denotes the TNode test
# 9 is the number of tests (the different ways we iterate)
# 2...12 denotes the number of arguments of the TNode we are iterating over
./perf_test_script 6 11 2 $@
./perf_test_script 6 11 3 $@
./perf_test_script 6 11 4 $@
./perf_test_script 6 11 5 $@
./perf_test_script 6 11 6 $@
./perf_test_script 6 11 7 $@
./perf_test_script 6 11 8 $@
./perf_test_script 6 11 9 $@
./perf_test_script 6 11 10 $@
./perf_test_script 6 11 11 $@
./perf_test_script 6 11 12 $@
