#!/bin/bash

echo "Run count Node tests with options $@..."

# 2 denotes the Node test
# 9 is the number of tests (the different ways we iterate)
# 2...12 denotes the number of arguments of the TNode we are iterating over
./perf_test_script 2 9 2 $@
./perf_test_script 2 9 3 $@
./perf_test_script 2 9 4 $@
./perf_test_script 2 9 5 $@
./perf_test_script 2 9 6 $@
./perf_test_script 2 9 7 $@
./perf_test_script 2 9 8 $@
./perf_test_script 2 9 9 $@
./perf_test_script 2 9 10 $@
./perf_test_script 2 9 11 $@
./perf_test_script 2 9 12 $@
