#!/bin/bash

# REQUIRES: input_problem.smt2
# REQUIRES: input_candidates.smt2

# OUTPUTS:

function mk_input_to_test_ic()
{
  echo "(set-logic ALL)"
  cat $1
  echo "(assert (input s t))"
  cat $2
  echo "(assert (IC s t))"
  echo "(check-sat)"
}

if grep -q define-fun input_candidates.smt2;
then
  # make new candidate, which is the last from the list in input_candidates.smt2
  tail -1 input_candidates.smt2 > temp_candidate.smt2

  echo "Visualizing candidate:"
  cat temp_candidate.smt2

  # generate the input problem for cvc4 to test a candidate IC
  mk_input_to_test_ic input_problem.smt2 temp_candidate.smt2 > temp_input_to_vis_ic.smt2

  # evaluate the candidate
  pr-ajr-cvc4 --test-ic-full --gen-ic-image --fmf-type-completion-thresh=2000 temp_input_to_vis_ic.smt2 > imgOut-candidate.ppm

  echo "...wrote file imgOut-candidate.ppm"

  # clean up
  rm -f temp_input_to_vis_ic.smt2
  rm -f temp_candidate.smt2
fi
