#!/bin/bash

# REQUIRES: input_grammar.sy
# REQUIRES: pbe_example_set.sy

# MODIFIES: input_candidates.smt2



# This generates a *.sy problem that corresponds to synthesizing the
# invertibility condition for the current approximate specification from
# $2 using the grammar from $1.
function mk_input_to_synth_ic()
{
  cat $1
  cat $2
  echo "(check-synth)"
}

# we generate better and better candidates over time, at some point we must quit

# generate the input problem for cvc4 to test a candidate IC
mk_input_to_synth_ic input_grammar.sy pbe_example_set.sy > temp_input_to_synth_ic.sy

# synthesize a new candidate
pr-ajr-cvc4 --sygus-stream --sygus-pbe $@ temp_input_to_synth_ic.sy > input_candidates.smt2

# we do not clean up input_candidates.smt2
if grep -q define-fun input_candidates.smt2;
then
  echo "***** Last candidate synthesized was:"
  tail -1 input_candidates.smt2
else
  echo "***** WARNING: no candidate synthesized!"
fi

# clean up
rm -f temp_input_to_synth_ic.sy
